enum tokens {
  NONE,
  LODD, STOD, ADDD, SUBD, JPOS, JZER, JUMP, LOCO,
  LODL, STOL, ADDL, SUBL, JNEG, JNZE, CALL, PSHI,
  POPI, PUSH, POP, RETN, SWAP, INSP, DESP, HALT,
  INTEG, JUNK, LABEL, LOC, STR };
