#define LODD    1
#define STOD    2
#define ADDD    3
#define SUBD    4
#define JPOS    5
#define JZER    6
#define JUMP    7
#define LOCO    8
#define LODL    9
#define STOL   10
#define ADDL   11
#define SUBL   12
#define JNEG   13
#define JNZE   14
#define CALL   15
#define PSHI   16
#define POPI   17
#define PUSH   18
#define POP    19
#define RETN   20
#define SWAP   21
#define INSP   22
#define DESP   23
#define HALT   24
#define INTEG  25
#define JUNK   26
#define LABEL  27
#define LOC    28
#define STR    29
